baseURL = "https://ajsmith.co/"
languageCode = "en-us"
title = "a j smith"
publishDir = "docs" 
enableGitInfo = true
footnoteReturnLinkContents = "â†©"
lastmod = [":fileModTime", ":default"] # auto populates lastmod date
pagination.pagerSize = 20

[taxonomies]
  tag = "tags"

[params]
  _merge = "deep"
  analyticsid = ""
  additionalmetatags = "<meta name=\"msvalidate.01\" content=\"\" />" 
  contactformEndpoint = "https://submit-form.com/TMzsthUG"
  contactformAdditionalCode= "<input type=\"hidden\" name=\"_redirect\" value=\"https://ajsmith.co/thankyou\"/>"
  botpoisonPublicKey = "pk_ceb1f068-0be7-467b-b9c5-3c722f2d4627" 
# another possible color scheme: 493829/eb8f0c
# also see internalpointers.com

# theming and reusable code
[module]
  _merge = "deep"
  [[module.imports]]
    path = "github.com/ajsmith607/undergo"
 
[markup]
  _merge = "deep"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
